// flow-typed signature: 2ed3673aa91430e94f042ef63bfac9b4
// flow-typed version: <<STUB>>/spotify-web-api-js_v^1.5.1/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'spotify-web-api-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'spotify-web-api-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'spotify-web-api-js/src/spotify-web-api' {
  declare module.exports: any;
}

// Filename aliases
declare module 'spotify-web-api-js/src/spotify-web-api.js' {
  declare module.exports: $Exports<'spotify-web-api-js/src/spotify-web-api'>;
}
