// flow-typed signature: df2a16af0ab79e1933e896ed62312877
// flow-typed version: <<STUB>>/swiper_v^5.4.2/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'swiper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'swiper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'swiper/js/swiper.esm.browser.bundle' {
  declare module.exports: any;
}

declare module 'swiper/js/swiper.esm.browser.bundle.min' {
  declare module.exports: any;
}

declare module 'swiper/js/swiper.esm.bundle' {
  declare module.exports: any;
}

declare module 'swiper/js/swiper.esm' {
  declare module.exports: any;
}

declare module 'swiper/js/swiper' {
  declare module.exports: any;
}

declare module 'swiper/js/swiper.min' {
  declare module.exports: any;
}

declare module 'swiper/src/components/a11y/a11y' {
  declare module.exports: any;
}

declare module 'swiper/src/components/autoplay/autoplay' {
  declare module.exports: any;
}

declare module 'swiper/src/components/controller/controller' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/breakpoints/getBreakpoint' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/breakpoints' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/breakpoints/setBreakpoint' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/check-overflow' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/classes/addClasses' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/classes' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/classes/removeClasses' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/core-class' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/defaults' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/events' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/events/onClick' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/events/onResize' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/events/onScroll' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/events/onTouchEnd' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/events/onTouchMove' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/events/onTouchStart' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/grab-cursor' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/grab-cursor/setGrabCursor' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/grab-cursor/unsetGrabCursor' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/images' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/images/loadImage' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/images/preloadImages' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/loop' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/loop/loopCreate' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/loop/loopDestroy' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/loop/loopFix' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/manipulation/addSlide' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/manipulation/appendSlide' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/manipulation' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/manipulation/prependSlide' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/manipulation/removeAllSlides' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/manipulation/removeSlide' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/slide' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/slide/slideNext' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/slide/slidePrev' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/slide/slideReset' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/slide/slideTo' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/slide/slideToClickedSlide' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/slide/slideToClosest' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/slide/slideToLoop' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/transition' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/transition/setTransition' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/transition/transitionEnd' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/transition/transitionStart' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/translate/getTranslate' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/translate' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/translate/maxTranslate' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/translate/minTranslate' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/translate/setTranslate' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/translate/translateTo' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/update' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/update/updateActiveIndex' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/update/updateAutoHeight' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/update/updateClickedSlide' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/update/updateProgress' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/update/updateSize' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/update/updateSlides' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/update/updateSlidesClasses' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/update/updateSlidesOffset' {
  declare module.exports: any;
}

declare module 'swiper/src/components/core/update/updateSlidesProgress' {
  declare module.exports: any;
}

declare module 'swiper/src/components/effect-coverflow/effect-coverflow' {
  declare module.exports: any;
}

declare module 'swiper/src/components/effect-cube/effect-cube' {
  declare module.exports: any;
}

declare module 'swiper/src/components/effect-fade/effect-fade' {
  declare module.exports: any;
}

declare module 'swiper/src/components/effect-flip/effect-flip' {
  declare module.exports: any;
}

declare module 'swiper/src/components/hash-navigation/hash-navigation' {
  declare module.exports: any;
}

declare module 'swiper/src/components/history/history' {
  declare module.exports: any;
}

declare module 'swiper/src/components/keyboard/keyboard' {
  declare module.exports: any;
}

declare module 'swiper/src/components/lazy/lazy' {
  declare module.exports: any;
}

declare module 'swiper/src/components/mousewheel/mousewheel' {
  declare module.exports: any;
}

declare module 'swiper/src/components/navigation/navigation' {
  declare module.exports: any;
}

declare module 'swiper/src/components/pagination/pagination' {
  declare module.exports: any;
}

declare module 'swiper/src/components/parallax/parallax' {
  declare module.exports: any;
}

declare module 'swiper/src/components/scrollbar/scrollbar' {
  declare module.exports: any;
}

declare module 'swiper/src/components/thumbs/thumbs' {
  declare module.exports: any;
}

declare module 'swiper/src/components/virtual/virtual' {
  declare module.exports: any;
}

declare module 'swiper/src/components/zoom/zoom' {
  declare module.exports: any;
}

declare module 'swiper/src/less/plugin' {
  declare module.exports: any;
}

declare module 'swiper/src/modules/browser/browser' {
  declare module.exports: any;
}

declare module 'swiper/src/modules/device/device' {
  declare module.exports: any;
}

declare module 'swiper/src/modules/observer/observer' {
  declare module.exports: any;
}

declare module 'swiper/src/modules/resize/resize' {
  declare module.exports: any;
}

declare module 'swiper/src/modules/support/support' {
  declare module.exports: any;
}

declare module 'swiper/src/swiper' {
  declare module.exports: any;
}

declare module 'swiper/src/utils/browser' {
  declare module.exports: any;
}

declare module 'swiper/src/utils/class' {
  declare module.exports: any;
}

declare module 'swiper/src/utils/device' {
  declare module.exports: any;
}

declare module 'swiper/src/utils/dom' {
  declare module.exports: any;
}

declare module 'swiper/src/utils/support' {
  declare module.exports: any;
}

declare module 'swiper/src/utils/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'swiper/js/swiper.esm.browser.bundle.js' {
  declare module.exports: $Exports<'swiper/js/swiper.esm.browser.bundle'>;
}
declare module 'swiper/js/swiper.esm.browser.bundle.min.js' {
  declare module.exports: $Exports<'swiper/js/swiper.esm.browser.bundle.min'>;
}
declare module 'swiper/js/swiper.esm.bundle.js' {
  declare module.exports: $Exports<'swiper/js/swiper.esm.bundle'>;
}
declare module 'swiper/js/swiper.esm.js' {
  declare module.exports: $Exports<'swiper/js/swiper.esm'>;
}
declare module 'swiper/js/swiper.js' {
  declare module.exports: $Exports<'swiper/js/swiper'>;
}
declare module 'swiper/js/swiper.min.js' {
  declare module.exports: $Exports<'swiper/js/swiper.min'>;
}
declare module 'swiper/src/components/a11y/a11y.js' {
  declare module.exports: $Exports<'swiper/src/components/a11y/a11y'>;
}
declare module 'swiper/src/components/autoplay/autoplay.js' {
  declare module.exports: $Exports<'swiper/src/components/autoplay/autoplay'>;
}
declare module 'swiper/src/components/controller/controller.js' {
  declare module.exports: $Exports<'swiper/src/components/controller/controller'>;
}
declare module 'swiper/src/components/core/breakpoints/getBreakpoint.js' {
  declare module.exports: $Exports<'swiper/src/components/core/breakpoints/getBreakpoint'>;
}
declare module 'swiper/src/components/core/breakpoints/index' {
  declare module.exports: $Exports<'swiper/src/components/core/breakpoints'>;
}
declare module 'swiper/src/components/core/breakpoints/index.js' {
  declare module.exports: $Exports<'swiper/src/components/core/breakpoints'>;
}
declare module 'swiper/src/components/core/breakpoints/setBreakpoint.js' {
  declare module.exports: $Exports<'swiper/src/components/core/breakpoints/setBreakpoint'>;
}
declare module 'swiper/src/components/core/check-overflow/index' {
  declare module.exports: $Exports<'swiper/src/components/core/check-overflow'>;
}
declare module 'swiper/src/components/core/check-overflow/index.js' {
  declare module.exports: $Exports<'swiper/src/components/core/check-overflow'>;
}
declare module 'swiper/src/components/core/classes/addClasses.js' {
  declare module.exports: $Exports<'swiper/src/components/core/classes/addClasses'>;
}
declare module 'swiper/src/components/core/classes/index' {
  declare module.exports: $Exports<'swiper/src/components/core/classes'>;
}
declare module 'swiper/src/components/core/classes/index.js' {
  declare module.exports: $Exports<'swiper/src/components/core/classes'>;
}
declare module 'swiper/src/components/core/classes/removeClasses.js' {
  declare module.exports: $Exports<'swiper/src/components/core/classes/removeClasses'>;
}
declare module 'swiper/src/components/core/core-class.js' {
  declare module.exports: $Exports<'swiper/src/components/core/core-class'>;
}
declare module 'swiper/src/components/core/defaults.js' {
  declare module.exports: $Exports<'swiper/src/components/core/defaults'>;
}
declare module 'swiper/src/components/core/events/index' {
  declare module.exports: $Exports<'swiper/src/components/core/events'>;
}
declare module 'swiper/src/components/core/events/index.js' {
  declare module.exports: $Exports<'swiper/src/components/core/events'>;
}
declare module 'swiper/src/components/core/events/onClick.js' {
  declare module.exports: $Exports<'swiper/src/components/core/events/onClick'>;
}
declare module 'swiper/src/components/core/events/onResize.js' {
  declare module.exports: $Exports<'swiper/src/components/core/events/onResize'>;
}
declare module 'swiper/src/components/core/events/onScroll.js' {
  declare module.exports: $Exports<'swiper/src/components/core/events/onScroll'>;
}
declare module 'swiper/src/components/core/events/onTouchEnd.js' {
  declare module.exports: $Exports<'swiper/src/components/core/events/onTouchEnd'>;
}
declare module 'swiper/src/components/core/events/onTouchMove.js' {
  declare module.exports: $Exports<'swiper/src/components/core/events/onTouchMove'>;
}
declare module 'swiper/src/components/core/events/onTouchStart.js' {
  declare module.exports: $Exports<'swiper/src/components/core/events/onTouchStart'>;
}
declare module 'swiper/src/components/core/grab-cursor/index' {
  declare module.exports: $Exports<'swiper/src/components/core/grab-cursor'>;
}
declare module 'swiper/src/components/core/grab-cursor/index.js' {
  declare module.exports: $Exports<'swiper/src/components/core/grab-cursor'>;
}
declare module 'swiper/src/components/core/grab-cursor/setGrabCursor.js' {
  declare module.exports: $Exports<'swiper/src/components/core/grab-cursor/setGrabCursor'>;
}
declare module 'swiper/src/components/core/grab-cursor/unsetGrabCursor.js' {
  declare module.exports: $Exports<'swiper/src/components/core/grab-cursor/unsetGrabCursor'>;
}
declare module 'swiper/src/components/core/images/index' {
  declare module.exports: $Exports<'swiper/src/components/core/images'>;
}
declare module 'swiper/src/components/core/images/index.js' {
  declare module.exports: $Exports<'swiper/src/components/core/images'>;
}
declare module 'swiper/src/components/core/images/loadImage.js' {
  declare module.exports: $Exports<'swiper/src/components/core/images/loadImage'>;
}
declare module 'swiper/src/components/core/images/preloadImages.js' {
  declare module.exports: $Exports<'swiper/src/components/core/images/preloadImages'>;
}
declare module 'swiper/src/components/core/loop/index' {
  declare module.exports: $Exports<'swiper/src/components/core/loop'>;
}
declare module 'swiper/src/components/core/loop/index.js' {
  declare module.exports: $Exports<'swiper/src/components/core/loop'>;
}
declare module 'swiper/src/components/core/loop/loopCreate.js' {
  declare module.exports: $Exports<'swiper/src/components/core/loop/loopCreate'>;
}
declare module 'swiper/src/components/core/loop/loopDestroy.js' {
  declare module.exports: $Exports<'swiper/src/components/core/loop/loopDestroy'>;
}
declare module 'swiper/src/components/core/loop/loopFix.js' {
  declare module.exports: $Exports<'swiper/src/components/core/loop/loopFix'>;
}
declare module 'swiper/src/components/core/manipulation/addSlide.js' {
  declare module.exports: $Exports<'swiper/src/components/core/manipulation/addSlide'>;
}
declare module 'swiper/src/components/core/manipulation/appendSlide.js' {
  declare module.exports: $Exports<'swiper/src/components/core/manipulation/appendSlide'>;
}
declare module 'swiper/src/components/core/manipulation/index' {
  declare module.exports: $Exports<'swiper/src/components/core/manipulation'>;
}
declare module 'swiper/src/components/core/manipulation/index.js' {
  declare module.exports: $Exports<'swiper/src/components/core/manipulation'>;
}
declare module 'swiper/src/components/core/manipulation/prependSlide.js' {
  declare module.exports: $Exports<'swiper/src/components/core/manipulation/prependSlide'>;
}
declare module 'swiper/src/components/core/manipulation/removeAllSlides.js' {
  declare module.exports: $Exports<'swiper/src/components/core/manipulation/removeAllSlides'>;
}
declare module 'swiper/src/components/core/manipulation/removeSlide.js' {
  declare module.exports: $Exports<'swiper/src/components/core/manipulation/removeSlide'>;
}
declare module 'swiper/src/components/core/slide/index' {
  declare module.exports: $Exports<'swiper/src/components/core/slide'>;
}
declare module 'swiper/src/components/core/slide/index.js' {
  declare module.exports: $Exports<'swiper/src/components/core/slide'>;
}
declare module 'swiper/src/components/core/slide/slideNext.js' {
  declare module.exports: $Exports<'swiper/src/components/core/slide/slideNext'>;
}
declare module 'swiper/src/components/core/slide/slidePrev.js' {
  declare module.exports: $Exports<'swiper/src/components/core/slide/slidePrev'>;
}
declare module 'swiper/src/components/core/slide/slideReset.js' {
  declare module.exports: $Exports<'swiper/src/components/core/slide/slideReset'>;
}
declare module 'swiper/src/components/core/slide/slideTo.js' {
  declare module.exports: $Exports<'swiper/src/components/core/slide/slideTo'>;
}
declare module 'swiper/src/components/core/slide/slideToClickedSlide.js' {
  declare module.exports: $Exports<'swiper/src/components/core/slide/slideToClickedSlide'>;
}
declare module 'swiper/src/components/core/slide/slideToClosest.js' {
  declare module.exports: $Exports<'swiper/src/components/core/slide/slideToClosest'>;
}
declare module 'swiper/src/components/core/slide/slideToLoop.js' {
  declare module.exports: $Exports<'swiper/src/components/core/slide/slideToLoop'>;
}
declare module 'swiper/src/components/core/transition/index' {
  declare module.exports: $Exports<'swiper/src/components/core/transition'>;
}
declare module 'swiper/src/components/core/transition/index.js' {
  declare module.exports: $Exports<'swiper/src/components/core/transition'>;
}
declare module 'swiper/src/components/core/transition/setTransition.js' {
  declare module.exports: $Exports<'swiper/src/components/core/transition/setTransition'>;
}
declare module 'swiper/src/components/core/transition/transitionEnd.js' {
  declare module.exports: $Exports<'swiper/src/components/core/transition/transitionEnd'>;
}
declare module 'swiper/src/components/core/transition/transitionStart.js' {
  declare module.exports: $Exports<'swiper/src/components/core/transition/transitionStart'>;
}
declare module 'swiper/src/components/core/translate/getTranslate.js' {
  declare module.exports: $Exports<'swiper/src/components/core/translate/getTranslate'>;
}
declare module 'swiper/src/components/core/translate/index' {
  declare module.exports: $Exports<'swiper/src/components/core/translate'>;
}
declare module 'swiper/src/components/core/translate/index.js' {
  declare module.exports: $Exports<'swiper/src/components/core/translate'>;
}
declare module 'swiper/src/components/core/translate/maxTranslate.js' {
  declare module.exports: $Exports<'swiper/src/components/core/translate/maxTranslate'>;
}
declare module 'swiper/src/components/core/translate/minTranslate.js' {
  declare module.exports: $Exports<'swiper/src/components/core/translate/minTranslate'>;
}
declare module 'swiper/src/components/core/translate/setTranslate.js' {
  declare module.exports: $Exports<'swiper/src/components/core/translate/setTranslate'>;
}
declare module 'swiper/src/components/core/translate/translateTo.js' {
  declare module.exports: $Exports<'swiper/src/components/core/translate/translateTo'>;
}
declare module 'swiper/src/components/core/update/index' {
  declare module.exports: $Exports<'swiper/src/components/core/update'>;
}
declare module 'swiper/src/components/core/update/index.js' {
  declare module.exports: $Exports<'swiper/src/components/core/update'>;
}
declare module 'swiper/src/components/core/update/updateActiveIndex.js' {
  declare module.exports: $Exports<'swiper/src/components/core/update/updateActiveIndex'>;
}
declare module 'swiper/src/components/core/update/updateAutoHeight.js' {
  declare module.exports: $Exports<'swiper/src/components/core/update/updateAutoHeight'>;
}
declare module 'swiper/src/components/core/update/updateClickedSlide.js' {
  declare module.exports: $Exports<'swiper/src/components/core/update/updateClickedSlide'>;
}
declare module 'swiper/src/components/core/update/updateProgress.js' {
  declare module.exports: $Exports<'swiper/src/components/core/update/updateProgress'>;
}
declare module 'swiper/src/components/core/update/updateSize.js' {
  declare module.exports: $Exports<'swiper/src/components/core/update/updateSize'>;
}
declare module 'swiper/src/components/core/update/updateSlides.js' {
  declare module.exports: $Exports<'swiper/src/components/core/update/updateSlides'>;
}
declare module 'swiper/src/components/core/update/updateSlidesClasses.js' {
  declare module.exports: $Exports<'swiper/src/components/core/update/updateSlidesClasses'>;
}
declare module 'swiper/src/components/core/update/updateSlidesOffset.js' {
  declare module.exports: $Exports<'swiper/src/components/core/update/updateSlidesOffset'>;
}
declare module 'swiper/src/components/core/update/updateSlidesProgress.js' {
  declare module.exports: $Exports<'swiper/src/components/core/update/updateSlidesProgress'>;
}
declare module 'swiper/src/components/effect-coverflow/effect-coverflow.js' {
  declare module.exports: $Exports<'swiper/src/components/effect-coverflow/effect-coverflow'>;
}
declare module 'swiper/src/components/effect-cube/effect-cube.js' {
  declare module.exports: $Exports<'swiper/src/components/effect-cube/effect-cube'>;
}
declare module 'swiper/src/components/effect-fade/effect-fade.js' {
  declare module.exports: $Exports<'swiper/src/components/effect-fade/effect-fade'>;
}
declare module 'swiper/src/components/effect-flip/effect-flip.js' {
  declare module.exports: $Exports<'swiper/src/components/effect-flip/effect-flip'>;
}
declare module 'swiper/src/components/hash-navigation/hash-navigation.js' {
  declare module.exports: $Exports<'swiper/src/components/hash-navigation/hash-navigation'>;
}
declare module 'swiper/src/components/history/history.js' {
  declare module.exports: $Exports<'swiper/src/components/history/history'>;
}
declare module 'swiper/src/components/keyboard/keyboard.js' {
  declare module.exports: $Exports<'swiper/src/components/keyboard/keyboard'>;
}
declare module 'swiper/src/components/lazy/lazy.js' {
  declare module.exports: $Exports<'swiper/src/components/lazy/lazy'>;
}
declare module 'swiper/src/components/mousewheel/mousewheel.js' {
  declare module.exports: $Exports<'swiper/src/components/mousewheel/mousewheel'>;
}
declare module 'swiper/src/components/navigation/navigation.js' {
  declare module.exports: $Exports<'swiper/src/components/navigation/navigation'>;
}
declare module 'swiper/src/components/pagination/pagination.js' {
  declare module.exports: $Exports<'swiper/src/components/pagination/pagination'>;
}
declare module 'swiper/src/components/parallax/parallax.js' {
  declare module.exports: $Exports<'swiper/src/components/parallax/parallax'>;
}
declare module 'swiper/src/components/scrollbar/scrollbar.js' {
  declare module.exports: $Exports<'swiper/src/components/scrollbar/scrollbar'>;
}
declare module 'swiper/src/components/thumbs/thumbs.js' {
  declare module.exports: $Exports<'swiper/src/components/thumbs/thumbs'>;
}
declare module 'swiper/src/components/virtual/virtual.js' {
  declare module.exports: $Exports<'swiper/src/components/virtual/virtual'>;
}
declare module 'swiper/src/components/zoom/zoom.js' {
  declare module.exports: $Exports<'swiper/src/components/zoom/zoom'>;
}
declare module 'swiper/src/less/plugin.js' {
  declare module.exports: $Exports<'swiper/src/less/plugin'>;
}
declare module 'swiper/src/modules/browser/browser.js' {
  declare module.exports: $Exports<'swiper/src/modules/browser/browser'>;
}
declare module 'swiper/src/modules/device/device.js' {
  declare module.exports: $Exports<'swiper/src/modules/device/device'>;
}
declare module 'swiper/src/modules/observer/observer.js' {
  declare module.exports: $Exports<'swiper/src/modules/observer/observer'>;
}
declare module 'swiper/src/modules/resize/resize.js' {
  declare module.exports: $Exports<'swiper/src/modules/resize/resize'>;
}
declare module 'swiper/src/modules/support/support.js' {
  declare module.exports: $Exports<'swiper/src/modules/support/support'>;
}
declare module 'swiper/src/swiper.js' {
  declare module.exports: $Exports<'swiper/src/swiper'>;
}
declare module 'swiper/src/utils/browser.js' {
  declare module.exports: $Exports<'swiper/src/utils/browser'>;
}
declare module 'swiper/src/utils/class.js' {
  declare module.exports: $Exports<'swiper/src/utils/class'>;
}
declare module 'swiper/src/utils/device.js' {
  declare module.exports: $Exports<'swiper/src/utils/device'>;
}
declare module 'swiper/src/utils/dom.js' {
  declare module.exports: $Exports<'swiper/src/utils/dom'>;
}
declare module 'swiper/src/utils/support.js' {
  declare module.exports: $Exports<'swiper/src/utils/support'>;
}
declare module 'swiper/src/utils/utils.js' {
  declare module.exports: $Exports<'swiper/src/utils/utils'>;
}
