// flow-typed signature: 84a477f828492d701d5be6e4f7359ec0
// flow-typed version: <<STUB>>/xstate_v^4.10.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xstate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xstate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'xstate/dist/xstate.interpreter' {
  declare module.exports: any;
}

declare module 'xstate/dist/xstate' {
  declare module.exports: any;
}

declare module 'xstate/dist/xstate.web' {
  declare module.exports: any;
}

declare module 'xstate/es/_virtual/_tslib' {
  declare module.exports: any;
}

declare module 'xstate/es/actions' {
  declare module.exports: any;
}

declare module 'xstate/es/actionTypes' {
  declare module.exports: any;
}

declare module 'xstate/es/Actor' {
  declare module.exports: any;
}

declare module 'xstate/es/constants' {
  declare module.exports: any;
}

declare module 'xstate/es/devTools' {
  declare module.exports: any;
}

declare module 'xstate/es/environment' {
  declare module.exports: any;
}

declare module 'xstate/es' {
  declare module.exports: any;
}

declare module 'xstate/es/interpreter' {
  declare module.exports: any;
}

declare module 'xstate/es/Machine' {
  declare module.exports: any;
}

declare module 'xstate/es/mapState' {
  declare module.exports: any;
}

declare module 'xstate/es/match' {
  declare module.exports: any;
}

declare module 'xstate/es/registry' {
  declare module.exports: any;
}

declare module 'xstate/es/scheduler' {
  declare module.exports: any;
}

declare module 'xstate/es/State' {
  declare module.exports: any;
}

declare module 'xstate/es/StateNode' {
  declare module.exports: any;
}

declare module 'xstate/es/stateUtils' {
  declare module.exports: any;
}

declare module 'xstate/es/types' {
  declare module.exports: any;
}

declare module 'xstate/es/utils' {
  declare module.exports: any;
}

declare module 'xstate/lib/actions' {
  declare module.exports: any;
}

declare module 'xstate/lib/actionTypes' {
  declare module.exports: any;
}

declare module 'xstate/lib/Actor' {
  declare module.exports: any;
}

declare module 'xstate/lib/constants' {
  declare module.exports: any;
}

declare module 'xstate/lib/devTools' {
  declare module.exports: any;
}

declare module 'xstate/lib/each' {
  declare module.exports: any;
}

declare module 'xstate/lib/environment' {
  declare module.exports: any;
}

declare module 'xstate/lib' {
  declare module.exports: any;
}

declare module 'xstate/lib/interpreter' {
  declare module.exports: any;
}

declare module 'xstate/lib/invoke' {
  declare module.exports: any;
}

declare module 'xstate/lib/json' {
  declare module.exports: any;
}

declare module 'xstate/lib/Machine' {
  declare module.exports: any;
}

declare module 'xstate/lib/mapState' {
  declare module.exports: any;
}

declare module 'xstate/lib/match' {
  declare module.exports: any;
}

declare module 'xstate/lib/patterns' {
  declare module.exports: any;
}

declare module 'xstate/lib/registry' {
  declare module.exports: any;
}

declare module 'xstate/lib/scheduler' {
  declare module.exports: any;
}

declare module 'xstate/lib/scxml' {
  declare module.exports: any;
}

declare module 'xstate/lib/SimulatedClock' {
  declare module.exports: any;
}

declare module 'xstate/lib/State' {
  declare module.exports: any;
}

declare module 'xstate/lib/StateNode' {
  declare module.exports: any;
}

declare module 'xstate/lib/stateUtils' {
  declare module.exports: any;
}

declare module 'xstate/lib/types' {
  declare module.exports: any;
}

declare module 'xstate/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'xstate/dist/xstate.interpreter.js' {
  declare module.exports: $Exports<'xstate/dist/xstate.interpreter'>;
}
declare module 'xstate/dist/xstate.js' {
  declare module.exports: $Exports<'xstate/dist/xstate'>;
}
declare module 'xstate/dist/xstate.web.js' {
  declare module.exports: $Exports<'xstate/dist/xstate.web'>;
}
declare module 'xstate/es/_virtual/_tslib.js' {
  declare module.exports: $Exports<'xstate/es/_virtual/_tslib'>;
}
declare module 'xstate/es/actions.js' {
  declare module.exports: $Exports<'xstate/es/actions'>;
}
declare module 'xstate/es/actionTypes.js' {
  declare module.exports: $Exports<'xstate/es/actionTypes'>;
}
declare module 'xstate/es/Actor.js' {
  declare module.exports: $Exports<'xstate/es/Actor'>;
}
declare module 'xstate/es/constants.js' {
  declare module.exports: $Exports<'xstate/es/constants'>;
}
declare module 'xstate/es/devTools.js' {
  declare module.exports: $Exports<'xstate/es/devTools'>;
}
declare module 'xstate/es/environment.js' {
  declare module.exports: $Exports<'xstate/es/environment'>;
}
declare module 'xstate/es/index' {
  declare module.exports: $Exports<'xstate/es'>;
}
declare module 'xstate/es/index.js' {
  declare module.exports: $Exports<'xstate/es'>;
}
declare module 'xstate/es/interpreter.js' {
  declare module.exports: $Exports<'xstate/es/interpreter'>;
}
declare module 'xstate/es/Machine.js' {
  declare module.exports: $Exports<'xstate/es/Machine'>;
}
declare module 'xstate/es/mapState.js' {
  declare module.exports: $Exports<'xstate/es/mapState'>;
}
declare module 'xstate/es/match.js' {
  declare module.exports: $Exports<'xstate/es/match'>;
}
declare module 'xstate/es/registry.js' {
  declare module.exports: $Exports<'xstate/es/registry'>;
}
declare module 'xstate/es/scheduler.js' {
  declare module.exports: $Exports<'xstate/es/scheduler'>;
}
declare module 'xstate/es/State.js' {
  declare module.exports: $Exports<'xstate/es/State'>;
}
declare module 'xstate/es/StateNode.js' {
  declare module.exports: $Exports<'xstate/es/StateNode'>;
}
declare module 'xstate/es/stateUtils.js' {
  declare module.exports: $Exports<'xstate/es/stateUtils'>;
}
declare module 'xstate/es/types.js' {
  declare module.exports: $Exports<'xstate/es/types'>;
}
declare module 'xstate/es/utils.js' {
  declare module.exports: $Exports<'xstate/es/utils'>;
}
declare module 'xstate/lib/actions.js' {
  declare module.exports: $Exports<'xstate/lib/actions'>;
}
declare module 'xstate/lib/actionTypes.js' {
  declare module.exports: $Exports<'xstate/lib/actionTypes'>;
}
declare module 'xstate/lib/Actor.js' {
  declare module.exports: $Exports<'xstate/lib/Actor'>;
}
declare module 'xstate/lib/constants.js' {
  declare module.exports: $Exports<'xstate/lib/constants'>;
}
declare module 'xstate/lib/devTools.js' {
  declare module.exports: $Exports<'xstate/lib/devTools'>;
}
declare module 'xstate/lib/each.js' {
  declare module.exports: $Exports<'xstate/lib/each'>;
}
declare module 'xstate/lib/environment.js' {
  declare module.exports: $Exports<'xstate/lib/environment'>;
}
declare module 'xstate/lib/index' {
  declare module.exports: $Exports<'xstate/lib'>;
}
declare module 'xstate/lib/index.js' {
  declare module.exports: $Exports<'xstate/lib'>;
}
declare module 'xstate/lib/interpreter.js' {
  declare module.exports: $Exports<'xstate/lib/interpreter'>;
}
declare module 'xstate/lib/invoke.js' {
  declare module.exports: $Exports<'xstate/lib/invoke'>;
}
declare module 'xstate/lib/json.js' {
  declare module.exports: $Exports<'xstate/lib/json'>;
}
declare module 'xstate/lib/Machine.js' {
  declare module.exports: $Exports<'xstate/lib/Machine'>;
}
declare module 'xstate/lib/mapState.js' {
  declare module.exports: $Exports<'xstate/lib/mapState'>;
}
declare module 'xstate/lib/match.js' {
  declare module.exports: $Exports<'xstate/lib/match'>;
}
declare module 'xstate/lib/patterns.js' {
  declare module.exports: $Exports<'xstate/lib/patterns'>;
}
declare module 'xstate/lib/registry.js' {
  declare module.exports: $Exports<'xstate/lib/registry'>;
}
declare module 'xstate/lib/scheduler.js' {
  declare module.exports: $Exports<'xstate/lib/scheduler'>;
}
declare module 'xstate/lib/scxml.js' {
  declare module.exports: $Exports<'xstate/lib/scxml'>;
}
declare module 'xstate/lib/SimulatedClock.js' {
  declare module.exports: $Exports<'xstate/lib/SimulatedClock'>;
}
declare module 'xstate/lib/State.js' {
  declare module.exports: $Exports<'xstate/lib/State'>;
}
declare module 'xstate/lib/StateNode.js' {
  declare module.exports: $Exports<'xstate/lib/StateNode'>;
}
declare module 'xstate/lib/stateUtils.js' {
  declare module.exports: $Exports<'xstate/lib/stateUtils'>;
}
declare module 'xstate/lib/types.js' {
  declare module.exports: $Exports<'xstate/lib/types'>;
}
declare module 'xstate/lib/utils.js' {
  declare module.exports: $Exports<'xstate/lib/utils'>;
}
