jobs:
  restore_package_cache:
    steps:
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Fallback cache to be used
            - v1-npm-deps-
  save_package_cache:
    steps:
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  build:
    docker:
      - image: circleci/node:12.10.0
    steps:              
      - checkout
      - restore_package_cache
      - run: rm -rf package-lock.json node_modules
      - run: npm i
      - save_package_cache
      - run: npm run test
      - run: npm run build

workflows:
  version: 2.1
  test:
    branches:
      only:
        - develop
    steps:
      - build
      - run: ./node_modules/.bin/firebase deploy -P test --token "$FIREBASE_TOKEN"
  prod:
    branches:
      only:
        - master
    steps:
      - build
      - run: ./node_modules/.bin/firebase deploy -P prod --token "$FIREBASE_TOKEN"