version: 2.1

commands:
  restore_package_cache:
    steps:
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Fallback cache to be used
            - v1-npm-deps-
  save_package_cache:
    steps:
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

jobs:
  build:
    docker:
      - image: rodanato/music-project:0.0.1
    working_directory: ~/project
    steps:              
      - checkout
      - setup_remote_docker
      - run: apk add docker-cli
      - run: |
          TAG="0.0.1"
          docker build -t rodanato/music-project:$TAG .
          docker login -u rodanato -p Intheclub7!
          docker push rodanato/music-project:$TAG

      # - restore_package_cache
      # - run: rm package-lock.json 
      # - run: npm i
      # - save_package_cache
      # - run: npm run test
      # - run: npm run build
  deploy_to_test:
    docker:
      - image: rodanato/music-project:0.0.1
    # working_directory: ~/project
    steps:
      # - run: curl -sL firebase.tools | bash
      # - run: ls
      # - run: firebase deploy -P test --token=$FIREBASE_TOKEN
      - run: ./node_modules/.bin/firebase deploy -P test --token=$FIREBASE_TOKEN
  deploy_to_prod:
    docker:
      - image: rodanato/music-project:0.0.1
    steps:
      # - run: curl -sL firebase.tools | bash
      - run: ./node_modules/.bin/firebase deploy -P prod --token=$FIREBASE_TOKEN

workflows:
  version: 2.1
  test:
    jobs:
      - build:
          filters:
            branches:
              only: develop
      - deploy_to_test:
          requires:
            - build
  prod:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy_to_prod:
          requires:
            - build
