// flow-typed signature: 2199fb1ab98177e8e9478bcdc7bc323f
// flow-typed version: <<STUB>>/@xstate/react_v^0.8.1/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@xstate/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@xstate/react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@xstate/react/lib/fsm' {
  declare module.exports: any;
}

declare module '@xstate/react/lib' {
  declare module.exports: any;
}

declare module '@xstate/react/lib/useActor' {
  declare module.exports: any;
}

// Filename aliases
declare module '@xstate/react/lib/fsm.js' {
  declare module.exports: $Exports<'@xstate/react/lib/fsm'>;
}
declare module '@xstate/react/lib/index' {
  declare module.exports: $Exports<'@xstate/react/lib'>;
}
declare module '@xstate/react/lib/index.js' {
  declare module.exports: $Exports<'@xstate/react/lib'>;
}
declare module '@xstate/react/lib/useActor.js' {
  declare module.exports: $Exports<'@xstate/react/lib/useActor'>;
}
