// flow-typed signature: 68c94e2d527253c3c482ae2a2e74f22c
// flow-typed version: <<STUB>>/@xstate/test_v^0.4.1/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@xstate/test'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@xstate/test' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@xstate/test/es' {
  declare module.exports: any;
}

declare module '@xstate/test/es/slimChalk.browser' {
  declare module.exports: any;
}

declare module '@xstate/test/es/slimChalk' {
  declare module.exports: any;
}

declare module '@xstate/test/es/types' {
  declare module.exports: any;
}

declare module '@xstate/test/lib' {
  declare module.exports: any;
}

declare module '@xstate/test/lib/slimChalk.browser' {
  declare module.exports: any;
}

declare module '@xstate/test/lib/slimChalk' {
  declare module.exports: any;
}

declare module '@xstate/test/lib/types' {
  declare module.exports: any;
}

// Filename aliases
declare module '@xstate/test/es/index' {
  declare module.exports: $Exports<'@xstate/test/es'>;
}
declare module '@xstate/test/es/index.js' {
  declare module.exports: $Exports<'@xstate/test/es'>;
}
declare module '@xstate/test/es/slimChalk.browser.js' {
  declare module.exports: $Exports<'@xstate/test/es/slimChalk.browser'>;
}
declare module '@xstate/test/es/slimChalk.js' {
  declare module.exports: $Exports<'@xstate/test/es/slimChalk'>;
}
declare module '@xstate/test/es/types.js' {
  declare module.exports: $Exports<'@xstate/test/es/types'>;
}
declare module '@xstate/test/lib/index' {
  declare module.exports: $Exports<'@xstate/test/lib'>;
}
declare module '@xstate/test/lib/index.js' {
  declare module.exports: $Exports<'@xstate/test/lib'>;
}
declare module '@xstate/test/lib/slimChalk.browser.js' {
  declare module.exports: $Exports<'@xstate/test/lib/slimChalk.browser'>;
}
declare module '@xstate/test/lib/slimChalk.js' {
  declare module.exports: $Exports<'@xstate/test/lib/slimChalk'>;
}
declare module '@xstate/test/lib/types.js' {
  declare module.exports: $Exports<'@xstate/test/lib/types'>;
}
